#!/bin/bash

. driglibash-base

root_or_die


run cp $(where)/scrutation /bin/

cat $(where)/scrutation.service | sed "s#echo#$@" > /etc/systemd/system/scrutation.service

run systemctl enable scrutation

run systemctl start scrutation
